# Generated by Django 2.0.3 on 2018-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0002_auto_20180324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
