# Generated by Django 2.0.3 on 2018-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0006_auto_20180325_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(limit_choices_to={'group': (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'))}, null=True, to='timk.Team'),
        ),
    ]
