# Generated by Django 2.0.3 on 2018-03-27 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0009_auto_20180325_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
