# Generated by Django 2.0.3 on 2018-03-28 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0011_auto_20180327_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=140, unique=True),
        ),
    ]
