# Generated by Django 2.0.3 on 2018-03-30 14:03

import autoslug.fields
from django.db import migrations
import timk.models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0012_auto_20180328_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=timk.models.get_populate_from, unique=True),
        ),
    ]
