# Generated by Django 2.0.3 on 2018-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0013_auto_20180330_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='stadium',
            new_name='venue',
        ),
    ]
