# Generated by Django 2.0.3 on 2018-04-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0016_auto_20180414_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
