# Generated by Django 2.0.3 on 2018-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0017_auto_20180414_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_code',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
