# Generated by Django 2.0.3 on 2018-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0018_auto_20180414_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
