# Generated by Django 2.0.3 on 2018-04-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('timk', '0019_auto_20180414_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stadium',
            new_name='Venue',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.AddField(
            model_name='sport',
            name='duration',
            field=models.TimeField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
