# Generated by Django 2.0.3 on 2018-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timk', '0021_auto_20180415_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='duration',
        ),
    ]
